### ISSUE TITLE
game errors out upon disconnect

### ISSUE THREAD

**Issue by mid-kid** [REONTeam/libmobile-bgb#2]
When ending a p2p battle, one of the parties frequently gets an error screen
https://www.vidlii.com/usfi/v/YZlzkRSjA0D.5wegSRZUf1wvJakRjXG-CkpNIXxrz90UR94834RG9jVAGi8h0HtfAIymn38iabtAkj_kj4YYmZNJMDMw.mp4

I thought I'd fixed this, but it's still a frequent occurrence on windows.

**Comment by DamienDoury** [comment]
Add the time code please

**Comment by gb-mobile** [comment]
Error occurs just after 4:30.

**Comment by mid-kid** [comment]
Fixed in v0.2.2. Games don't expect to receive an error when the remote has disconnected in p2p mode. Apparently the adapter never checked for disconnection like this. Maybe it was done through the CHECK_STATUS command?
