### ISSUE TITLE
mobile.exe giver error 02 when trying to connect in mobile trainer

### ISSUE THREAD

**Issue by pokemonfan6498** [REONTeam/libmobile-bgb#3]
i was trying to test the program with bgb but when i tried to connect to dion the console shown error 02 which caused error 24-000 to appear in mobile trainer maybe it's related to status of program being disconnected

**Comment by MatandoYT** [comment]
Please seek assistance on our Discord server. The issue tracker here is only for issues with the program itself and not usage. Please provide logs, screenshots, and more to help us help you.

https://discord.com/invite/xepaQrHR
